name: AutoSprint
main: com.miyozmc.nukkit.autosprint.AutoSprint
version: 1.0.0
load: POSTWORLD
author: MiyozMC
api: ["1.0.0"]

description: A simple AutoSprint Plugin for nukkit
website: miyozmc.pages.dev